=== Martin-Ludwig/962102091b63691ac55ea3e91d8b998e/V5/lib/xml/schema/skills.xsd
<!--
02.03.2020
Generated by https://www.freeformatter.com/xsd-generator.html
    and modified by Martin Ludwig
-->


<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified">
    <xs:element name="skills">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="skill" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="name"/>
                            <xs:element type="xs:string" name="description"/>
                            <xs:element name="priority">
                                <xs:simpleType>
                                    <xs:restriction base="xs:byte">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="6"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            
                            <xs:element name="moduletype">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="type" maxOccurs="unbounded" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:integer" name="id" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="version" use="optional"/>
        </xs:complexType>
        <xs:unique name="skillID">
            <xs:selector xpath="skill"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>
</xs:schema>

=== Martin-Ludwig/962102091b63691ac55ea3e91d8b998e/V5/lib/xml/skills.xml
<?xml version="1.0" encoding="UTF-8"?>

<skills schemaLocation="schema/skills.xsd" version="02-03-2020">
    <skill id="1">
        <name>Example</name>
        <description>
            Lorem Ipsum ...
        </description>
        <priority>3</priority>
        <moduletype>
            <type>attack</type>
            <type>melee</type>
            <type>physical</type>
            <type>dagger</type>
        </moduletype>
    </skill>
    
    <skill id="2">
        <name>Example</name>
        <description>
            Lorem Ipsum ...
        </description>
        <priority>3</priority>
        <moduletype>
            <type>attack</type>
            <type>melee</type>
            <type>physical</type>
            <type>dagger</type>
        </moduletype>
    </skill>
</skills>
